# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0
# SPDX-License-Identifier: MIT

name: precommit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@4b90dec8413886f0137c1cd21468a85fc993c7c4 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@4b90dec8413886f0137c1cd21468a85fc993c7c4 # develop
