# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0
# SPDX-License-Identifier: MIT

name: auto-approve
on: pull_request

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: github.actor == 'xenoterracide'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
