# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: build
on: [push]
jobs:
  build:
    uses: xenoterracide/github/.github/workflows/maven.yml@018ff5dc09e3286599d259107ab8012f4ec338f2 # develop
    permissions:
      actions: write
      contents: read
      packages: read
  jbang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: "25"
          distribution: "temurin"
      - run: ./mvnw install -DskipTests -q --batch-mode
      - uses: jbangdev/setup-jbang@2b1b465a7b75f4222b81426f23a01e013aa7b95c # v0.1.1
      - run: jbang main.java --help
      - run: jbang main.java
