# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: build
on: [push]
jobs:
  build:
    uses: xenoterracide/github/.github/workflows/maven.yml@29a3d18797fea084c08dd6551099c1726baef8b4 # develop
    permissions:
      actions: write
      contents: read
      packages: read
  jbang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
      - run: ./mvnw install -DskipTests -q --batch-mode
      - uses: jbangdev/setup-jbang@v0.1.1
      - run: jbang main.java --help
      - run: jbang main.java
