# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: devtools-regression
on: push
permissions:
  contents: read
jobs:
  regression-prettier:
    uses: xenoterracide/github/.github/workflows/regression-devtool-prettier.yml@3871e178c388e3936a2ddd9f0cf92b4dceb42a2b # develop
  regression-lint-staged:
    uses: xenoterracide/github/.github/workflows/regression-devtool-lint-staged.yml@3871e178c388e3936a2ddd9f0cf92b4dceb42a2b # develop
  regression-git-conventional-commits:
    uses: xenoterracide/github/.github/workflows/regression-devtool-git-conventional-commits.yml@3871e178c388e3936a2ddd9f0cf92b4dceb42a2b # develop
  regression-reuse:
    uses: xenoterracide/github/.github/workflows/regression-devtool-reuse.yml@3871e178c388e3936a2ddd9f0cf92b4dceb42a2b # develop
