# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: devtools-regression
on: push
permissions:
  contents: read
jobs:
  node-cli:
    uses: xenoterracide/github/.github/workflows/node-cli.yml@114ac59868ed0f45eada1a7c2acdc013a2159320 # develop
