# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: devtools-regression
on: push
permissions:
  contents: read
jobs:
  node-cli:
    uses: xenoterracide/github/.github/workflows/node-cli.yml@a028f5e30549212ead1a5412c3bb69bf4bda8cbd # develop
