# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@99567d140cfe189e969cde6a29d7339daeca6006 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@99567d140cfe189e969cde6a29d7339daeca6006 # develop
