# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@dfd58ae626fcd4fd9a74971c46eb6c81e45e267e # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@dfd58ae626fcd4fd9a74971c46eb6c81e45e267e # develop
