# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@d193f6d0eeaabeaf29f397c56b32e4fbfcd87384 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@d193f6d0eeaabeaf29f397c56b32e4fbfcd87384 # develop
